name: VPS via Serveo

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest

    steps:
      - name: Installer les outils nécessaires
        run: sudo apt update && sudo apt install -y screen openssh-client

      - name: Lancer le tunnel SSH Serveo
        run: |
          screen -dmS tunnel ssh -o StrictHostKeyChecking=no -R 2222:localhost:22 serveo.net
          echo "Tunnel SSH lancé via Serveo"
          sleep 20

      - name: Afficher un message
        run: echo "Tunnel actif, connecte-toi sur serveo.net avec ssh -p 2222 utilisateur@serveo.net"
