name: VPS via Serveo

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest

    steps:
      - name: Installer les outils nécessaires
        run: sudo apt update && sudo apt install -y openssh-client

      - name: Lancer Serveo et garder le tunnel actif
        run: |
          echo "Connexion à Serveo..."
          ssh -o StrictHostKeyChecking=no -R 2222:localhost:22 serveo.net &
          echo "Tunnel ouvert. Attente infinie..."
          tail -f /dev/null
