name: VPS via Serveo

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest

    steps:
      - name: Installer SSH
        run: sudo apt update && sudo apt install -y openssh-client

      - name: Lancer tunnel SSH Serveo avec sous-domaine
        run: |
          echo "Connexion à Serveo..."
          ssh -o StrictHostKeyChecking=no -R feuyar:22:localhost:22 serveo.net &
          echo "Tunnel ouvert sur feuyar.serveo.net:22"
          tail -f /dev/null
